/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortailRouteImport } from './routes/portail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSondesRouteImport } from './routes/_authenticated/sondes'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedReglementsRouteImport } from './routes/_authenticated/reglements'
import { Route as AuthenticatedReferentielsRouteImport } from './routes/_authenticated/referentiels'
import { Route as AuthenticatedReceptionScanRouteImport } from './routes/_authenticated/reception-scan'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedQualiteRouteImport } from './routes/_authenticated/qualite'
import { Route as AuthenticatedProjetsRouteImport } from './routes/_authenticated/projets'
import { Route as AuthenticatedProduitsRouteImport } from './routes/_authenticated/produits'
import { Route as AuthenticatedPrelevementsRouteImport } from './routes/_authenticated/prelevements'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedMilieuxRouteImport } from './routes/_authenticated/milieux'
import { Route as AuthenticatedFeuillesRouteRouteImport } from './routes/_authenticated/feuilles-route'
import { Route as AuthenticatedFacturationRouteImport } from './routes/_authenticated/facturation'
import { Route as AuthenticatedEquipementsRouteImport } from './routes/_authenticated/equipements'
import { Route as AuthenticatedDevisRouteImport } from './routes/_authenticated/devis'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBonsCommandeRouteImport } from './routes/_authenticated/bons-commande'
import { Route as AuthenticatedAvoirsRouteImport } from './routes/_authenticated/avoirs'
import { Route as AuthenticatedAnalysesRouteImport } from './routes/_authenticated/analyses'
import { Route as ApiPublicSondesIngestRouteImport } from './routes/api/public/sondes/ingest'

const PortailRoute = PortailRouteImport.update({
  id: '/portail',
  path: '/portail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSondesRoute = AuthenticatedSondesRouteImport.update({
  id: '/sondes',
  path: '/sondes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReglementsRoute = AuthenticatedReglementsRouteImport.update({
  id: '/reglements',
  path: '/reglements',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferentielsRoute =
  AuthenticatedReferentielsRouteImport.update({
    id: '/referentiels',
    path: '/referentiels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceptionScanRoute =
  AuthenticatedReceptionScanRouteImport.update({
    id: '/reception-scan',
    path: '/reception-scan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQualiteRoute = AuthenticatedQualiteRouteImport.update({
  id: '/qualite',
  path: '/qualite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetsRoute = AuthenticatedProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProduitsRoute = AuthenticatedProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrelevementsRoute =
  AuthenticatedPrelevementsRouteImport.update({
    id: '/prelevements',
    path: '/prelevements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMilieuxRoute = AuthenticatedMilieuxRouteImport.update({
  id: '/milieux',
  path: '/milieux',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeuillesRouteRoute =
  AuthenticatedFeuillesRouteRouteImport.update({
    id: '/feuilles-route',
    path: '/feuilles-route',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationRoute =
  AuthenticatedFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipementsRoute =
  AuthenticatedEquipementsRouteImport.update({
    id: '/equipements',
    path: '/equipements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevisRoute = AuthenticatedDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBonsCommandeRoute =
  AuthenticatedBonsCommandeRouteImport.update({
    id: '/bons-commande',
    path: '/bons-commande',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvoirsRoute = AuthenticatedAvoirsRouteImport.update({
  id: '/avoirs',
  path: '/avoirs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysesRoute = AuthenticatedAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSondesIngestRoute = ApiPublicSondesIngestRouteImport.update({
  id: '/api/public/sondes/ingest',
  path: '/api/public/sondes/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/portail': typeof PortailRoute
  '/analyses': typeof AuthenticatedAnalysesRoute
  '/avoirs': typeof AuthenticatedAvoirsRoute
  '/bons-commande': typeof AuthenticatedBonsCommandeRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/equipements': typeof AuthenticatedEquipementsRoute
  '/facturation': typeof AuthenticatedFacturationRoute
  '/feuilles-route': typeof AuthenticatedFeuillesRouteRoute
  '/milieux': typeof AuthenticatedMilieuxRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/prelevements': typeof AuthenticatedPrelevementsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/qualite': typeof AuthenticatedQualiteRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/reception-scan': typeof AuthenticatedReceptionScanRoute
  '/referentiels': typeof AuthenticatedReferentielsRoute
  '/reglements': typeof AuthenticatedReglementsRoute
  '/rh': typeof AuthenticatedRhRoute
  '/sondes': typeof AuthenticatedSondesRoute
  '/api/public/sondes/ingest': typeof ApiPublicSondesIngestRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/portail': typeof PortailRoute
  '/analyses': typeof AuthenticatedAnalysesRoute
  '/avoirs': typeof AuthenticatedAvoirsRoute
  '/bons-commande': typeof AuthenticatedBonsCommandeRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/equipements': typeof AuthenticatedEquipementsRoute
  '/facturation': typeof AuthenticatedFacturationRoute
  '/feuilles-route': typeof AuthenticatedFeuillesRouteRoute
  '/milieux': typeof AuthenticatedMilieuxRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/prelevements': typeof AuthenticatedPrelevementsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/qualite': typeof AuthenticatedQualiteRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/reception-scan': typeof AuthenticatedReceptionScanRoute
  '/referentiels': typeof AuthenticatedReferentielsRoute
  '/reglements': typeof AuthenticatedReglementsRoute
  '/rh': typeof AuthenticatedRhRoute
  '/sondes': typeof AuthenticatedSondesRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/sondes/ingest': typeof ApiPublicSondesIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/portail': typeof PortailRoute
  '/_authenticated/analyses': typeof AuthenticatedAnalysesRoute
  '/_authenticated/avoirs': typeof AuthenticatedAvoirsRoute
  '/_authenticated/bons-commande': typeof AuthenticatedBonsCommandeRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/devis': typeof AuthenticatedDevisRoute
  '/_authenticated/equipements': typeof AuthenticatedEquipementsRoute
  '/_authenticated/facturation': typeof AuthenticatedFacturationRoute
  '/_authenticated/feuilles-route': typeof AuthenticatedFeuillesRouteRoute
  '/_authenticated/milieux': typeof AuthenticatedMilieuxRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/prelevements': typeof AuthenticatedPrelevementsRoute
  '/_authenticated/produits': typeof AuthenticatedProduitsRoute
  '/_authenticated/projets': typeof AuthenticatedProjetsRoute
  '/_authenticated/qualite': typeof AuthenticatedQualiteRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/reception-scan': typeof AuthenticatedReceptionScanRoute
  '/_authenticated/referentiels': typeof AuthenticatedReferentielsRoute
  '/_authenticated/reglements': typeof AuthenticatedReglementsRoute
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/_authenticated/sondes': typeof AuthenticatedSondesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/sondes/ingest': typeof ApiPublicSondesIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portail'
    | '/analyses'
    | '/avoirs'
    | '/bons-commande'
    | '/clients'
    | '/devis'
    | '/equipements'
    | '/facturation'
    | '/feuilles-route'
    | '/milieux'
    | '/missions'
    | '/notifications'
    | '/parametres'
    | '/prelevements'
    | '/produits'
    | '/projets'
    | '/qualite'
    | '/rapports'
    | '/reception-scan'
    | '/referentiels'
    | '/reglements'
    | '/rh'
    | '/sondes'
    | '/api/public/sondes/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/portail'
    | '/analyses'
    | '/avoirs'
    | '/bons-commande'
    | '/clients'
    | '/devis'
    | '/equipements'
    | '/facturation'
    | '/feuilles-route'
    | '/milieux'
    | '/missions'
    | '/notifications'
    | '/parametres'
    | '/prelevements'
    | '/produits'
    | '/projets'
    | '/qualite'
    | '/rapports'
    | '/reception-scan'
    | '/referentiels'
    | '/reglements'
    | '/rh'
    | '/sondes'
    | '/'
    | '/api/public/sondes/ingest'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/portail'
    | '/_authenticated/analyses'
    | '/_authenticated/avoirs'
    | '/_authenticated/bons-commande'
    | '/_authenticated/clients'
    | '/_authenticated/devis'
    | '/_authenticated/equipements'
    | '/_authenticated/facturation'
    | '/_authenticated/feuilles-route'
    | '/_authenticated/milieux'
    | '/_authenticated/missions'
    | '/_authenticated/notifications'
    | '/_authenticated/parametres'
    | '/_authenticated/prelevements'
    | '/_authenticated/produits'
    | '/_authenticated/projets'
    | '/_authenticated/qualite'
    | '/_authenticated/rapports'
    | '/_authenticated/reception-scan'
    | '/_authenticated/referentiels'
    | '/_authenticated/reglements'
    | '/_authenticated/rh'
    | '/_authenticated/sondes'
    | '/_authenticated/'
    | '/api/public/sondes/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortailRoute: typeof PortailRoute
  ApiPublicSondesIngestRoute: typeof ApiPublicSondesIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portail': {
      id: '/portail'
      path: '/portail'
      fullPath: '/portail'
      preLoaderRoute: typeof PortailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sondes': {
      id: '/_authenticated/sondes'
      path: '/sondes'
      fullPath: '/sondes'
      preLoaderRoute: typeof AuthenticatedSondesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reglements': {
      id: '/_authenticated/reglements'
      path: '/reglements'
      fullPath: '/reglements'
      preLoaderRoute: typeof AuthenticatedReglementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referentiels': {
      id: '/_authenticated/referentiels'
      path: '/referentiels'
      fullPath: '/referentiels'
      preLoaderRoute: typeof AuthenticatedReferentielsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reception-scan': {
      id: '/_authenticated/reception-scan'
      path: '/reception-scan'
      fullPath: '/reception-scan'
      preLoaderRoute: typeof AuthenticatedReceptionScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qualite': {
      id: '/_authenticated/qualite'
      path: '/qualite'
      fullPath: '/qualite'
      preLoaderRoute: typeof AuthenticatedQualiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projets': {
      id: '/_authenticated/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedProjetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produits': {
      id: '/_authenticated/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AuthenticatedProduitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prelevements': {
      id: '/_authenticated/prelevements'
      path: '/prelevements'
      fullPath: '/prelevements'
      preLoaderRoute: typeof AuthenticatedPrelevementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/milieux': {
      id: '/_authenticated/milieux'
      path: '/milieux'
      fullPath: '/milieux'
      preLoaderRoute: typeof AuthenticatedMilieuxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feuilles-route': {
      id: '/_authenticated/feuilles-route'
      path: '/feuilles-route'
      fullPath: '/feuilles-route'
      preLoaderRoute: typeof AuthenticatedFeuillesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation': {
      id: '/_authenticated/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof AuthenticatedFacturationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipements': {
      id: '/_authenticated/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof AuthenticatedEquipementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis': {
      id: '/_authenticated/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthenticatedDevisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bons-commande': {
      id: '/_authenticated/bons-commande'
      path: '/bons-commande'
      fullPath: '/bons-commande'
      preLoaderRoute: typeof AuthenticatedBonsCommandeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avoirs': {
      id: '/_authenticated/avoirs'
      path: '/avoirs'
      fullPath: '/avoirs'
      preLoaderRoute: typeof AuthenticatedAvoirsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses': {
      id: '/_authenticated/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AuthenticatedAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sondes/ingest': {
      id: '/api/public/sondes/ingest'
      path: '/api/public/sondes/ingest'
      fullPath: '/api/public/sondes/ingest'
      preLoaderRoute: typeof ApiPublicSondesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalysesRoute: typeof AuthenticatedAnalysesRoute
  AuthenticatedAvoirsRoute: typeof AuthenticatedAvoirsRoute
  AuthenticatedBonsCommandeRoute: typeof AuthenticatedBonsCommandeRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDevisRoute: typeof AuthenticatedDevisRoute
  AuthenticatedEquipementsRoute: typeof AuthenticatedEquipementsRoute
  AuthenticatedFacturationRoute: typeof AuthenticatedFacturationRoute
  AuthenticatedFeuillesRouteRoute: typeof AuthenticatedFeuillesRouteRoute
  AuthenticatedMilieuxRoute: typeof AuthenticatedMilieuxRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPrelevementsRoute: typeof AuthenticatedPrelevementsRoute
  AuthenticatedProduitsRoute: typeof AuthenticatedProduitsRoute
  AuthenticatedProjetsRoute: typeof AuthenticatedProjetsRoute
  AuthenticatedQualiteRoute: typeof AuthenticatedQualiteRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedReceptionScanRoute: typeof AuthenticatedReceptionScanRoute
  AuthenticatedReferentielsRoute: typeof AuthenticatedReferentielsRoute
  AuthenticatedReglementsRoute: typeof AuthenticatedReglementsRoute
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedSondesRoute: typeof AuthenticatedSondesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalysesRoute: AuthenticatedAnalysesRoute,
  AuthenticatedAvoirsRoute: AuthenticatedAvoirsRoute,
  AuthenticatedBonsCommandeRoute: AuthenticatedBonsCommandeRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDevisRoute: AuthenticatedDevisRoute,
  AuthenticatedEquipementsRoute: AuthenticatedEquipementsRoute,
  AuthenticatedFacturationRoute: AuthenticatedFacturationRoute,
  AuthenticatedFeuillesRouteRoute: AuthenticatedFeuillesRouteRoute,
  AuthenticatedMilieuxRoute: AuthenticatedMilieuxRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPrelevementsRoute: AuthenticatedPrelevementsRoute,
  AuthenticatedProduitsRoute: AuthenticatedProduitsRoute,
  AuthenticatedProjetsRoute: AuthenticatedProjetsRoute,
  AuthenticatedQualiteRoute: AuthenticatedQualiteRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedReceptionScanRoute: AuthenticatedReceptionScanRoute,
  AuthenticatedReferentielsRoute: AuthenticatedReferentielsRoute,
  AuthenticatedReglementsRoute: AuthenticatedReglementsRoute,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedSondesRoute: AuthenticatedSondesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortailRoute: PortailRoute,
  ApiPublicSondesIngestRoute: ApiPublicSondesIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
