/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortailRouteImport } from './routes/portail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedQualiteRouteImport } from './routes/_authenticated/qualite'
import { Route as AuthenticatedProjetsRouteImport } from './routes/_authenticated/projets'
import { Route as AuthenticatedProduitsRouteImport } from './routes/_authenticated/produits'
import { Route as AuthenticatedPrelevementsRouteImport } from './routes/_authenticated/prelevements'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedFeuillesRouteRouteImport } from './routes/_authenticated/feuilles-route'
import { Route as AuthenticatedFacturationRouteImport } from './routes/_authenticated/facturation'
import { Route as AuthenticatedEquipementsRouteImport } from './routes/_authenticated/equipements'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBonsCommandeRouteImport } from './routes/_authenticated/bons-commande'
import { Route as AuthenticatedAnalysesRouteImport } from './routes/_authenticated/analyses'

const PortailRoute = PortailRouteImport.update({
  id: '/portail',
  path: '/portail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQualiteRoute = AuthenticatedQualiteRouteImport.update({
  id: '/qualite',
  path: '/qualite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetsRoute = AuthenticatedProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProduitsRoute = AuthenticatedProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrelevementsRoute =
  AuthenticatedPrelevementsRouteImport.update({
    id: '/prelevements',
    path: '/prelevements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeuillesRouteRoute =
  AuthenticatedFeuillesRouteRouteImport.update({
    id: '/feuilles-route',
    path: '/feuilles-route',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationRoute =
  AuthenticatedFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipementsRoute =
  AuthenticatedEquipementsRouteImport.update({
    id: '/equipements',
    path: '/equipements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBonsCommandeRoute =
  AuthenticatedBonsCommandeRouteImport.update({
    id: '/bons-commande',
    path: '/bons-commande',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalysesRoute = AuthenticatedAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/portail': typeof PortailRoute
  '/analyses': typeof AuthenticatedAnalysesRoute
  '/bons-commande': typeof AuthenticatedBonsCommandeRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/equipements': typeof AuthenticatedEquipementsRoute
  '/facturation': typeof AuthenticatedFacturationRoute
  '/feuilles-route': typeof AuthenticatedFeuillesRouteRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/prelevements': typeof AuthenticatedPrelevementsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/qualite': typeof AuthenticatedQualiteRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/rh': typeof AuthenticatedRhRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/portail': typeof PortailRoute
  '/analyses': typeof AuthenticatedAnalysesRoute
  '/bons-commande': typeof AuthenticatedBonsCommandeRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/equipements': typeof AuthenticatedEquipementsRoute
  '/facturation': typeof AuthenticatedFacturationRoute
  '/feuilles-route': typeof AuthenticatedFeuillesRouteRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/prelevements': typeof AuthenticatedPrelevementsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/qualite': typeof AuthenticatedQualiteRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/rh': typeof AuthenticatedRhRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/portail': typeof PortailRoute
  '/_authenticated/analyses': typeof AuthenticatedAnalysesRoute
  '/_authenticated/bons-commande': typeof AuthenticatedBonsCommandeRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/equipements': typeof AuthenticatedEquipementsRoute
  '/_authenticated/facturation': typeof AuthenticatedFacturationRoute
  '/_authenticated/feuilles-route': typeof AuthenticatedFeuillesRouteRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/prelevements': typeof AuthenticatedPrelevementsRoute
  '/_authenticated/produits': typeof AuthenticatedProduitsRoute
  '/_authenticated/projets': typeof AuthenticatedProjetsRoute
  '/_authenticated/qualite': typeof AuthenticatedQualiteRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portail'
    | '/analyses'
    | '/bons-commande'
    | '/clients'
    | '/equipements'
    | '/facturation'
    | '/feuilles-route'
    | '/missions'
    | '/notifications'
    | '/parametres'
    | '/prelevements'
    | '/produits'
    | '/projets'
    | '/qualite'
    | '/rapports'
    | '/rh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/portail'
    | '/analyses'
    | '/bons-commande'
    | '/clients'
    | '/equipements'
    | '/facturation'
    | '/feuilles-route'
    | '/missions'
    | '/notifications'
    | '/parametres'
    | '/prelevements'
    | '/produits'
    | '/projets'
    | '/qualite'
    | '/rapports'
    | '/rh'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/portail'
    | '/_authenticated/analyses'
    | '/_authenticated/bons-commande'
    | '/_authenticated/clients'
    | '/_authenticated/equipements'
    | '/_authenticated/facturation'
    | '/_authenticated/feuilles-route'
    | '/_authenticated/missions'
    | '/_authenticated/notifications'
    | '/_authenticated/parametres'
    | '/_authenticated/prelevements'
    | '/_authenticated/produits'
    | '/_authenticated/projets'
    | '/_authenticated/qualite'
    | '/_authenticated/rapports'
    | '/_authenticated/rh'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortailRoute: typeof PortailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portail': {
      id: '/portail'
      path: '/portail'
      fullPath: '/portail'
      preLoaderRoute: typeof PortailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qualite': {
      id: '/_authenticated/qualite'
      path: '/qualite'
      fullPath: '/qualite'
      preLoaderRoute: typeof AuthenticatedQualiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projets': {
      id: '/_authenticated/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedProjetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produits': {
      id: '/_authenticated/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AuthenticatedProduitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prelevements': {
      id: '/_authenticated/prelevements'
      path: '/prelevements'
      fullPath: '/prelevements'
      preLoaderRoute: typeof AuthenticatedPrelevementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feuilles-route': {
      id: '/_authenticated/feuilles-route'
      path: '/feuilles-route'
      fullPath: '/feuilles-route'
      preLoaderRoute: typeof AuthenticatedFeuillesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation': {
      id: '/_authenticated/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof AuthenticatedFacturationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipements': {
      id: '/_authenticated/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof AuthenticatedEquipementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bons-commande': {
      id: '/_authenticated/bons-commande'
      path: '/bons-commande'
      fullPath: '/bons-commande'
      preLoaderRoute: typeof AuthenticatedBonsCommandeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses': {
      id: '/_authenticated/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AuthenticatedAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalysesRoute: typeof AuthenticatedAnalysesRoute
  AuthenticatedBonsCommandeRoute: typeof AuthenticatedBonsCommandeRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedEquipementsRoute: typeof AuthenticatedEquipementsRoute
  AuthenticatedFacturationRoute: typeof AuthenticatedFacturationRoute
  AuthenticatedFeuillesRouteRoute: typeof AuthenticatedFeuillesRouteRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPrelevementsRoute: typeof AuthenticatedPrelevementsRoute
  AuthenticatedProduitsRoute: typeof AuthenticatedProduitsRoute
  AuthenticatedProjetsRoute: typeof AuthenticatedProjetsRoute
  AuthenticatedQualiteRoute: typeof AuthenticatedQualiteRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalysesRoute: AuthenticatedAnalysesRoute,
  AuthenticatedBonsCommandeRoute: AuthenticatedBonsCommandeRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedEquipementsRoute: AuthenticatedEquipementsRoute,
  AuthenticatedFacturationRoute: AuthenticatedFacturationRoute,
  AuthenticatedFeuillesRouteRoute: AuthenticatedFeuillesRouteRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPrelevementsRoute: AuthenticatedPrelevementsRoute,
  AuthenticatedProduitsRoute: AuthenticatedProduitsRoute,
  AuthenticatedProjetsRoute: AuthenticatedProjetsRoute,
  AuthenticatedQualiteRoute: AuthenticatedQualiteRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortailRoute: PortailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
